export const recetasCocina = [
    {
      id:1,
      nombre: 'Pollo al horno con papas',
      ingredientes: [
        '1 pollo entero',
        '4 papas',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
        'Hierbas aromáticas (opcional)',
        'Limón (opcional)',
      ],
      pasos: [
        'Precalienta el horno a 180°C (350°F).',
        'Lava y corta las papas en trozos.',
        'Coloca el pollo en una bandeja para hornear y añade las papas alrededor.',
        'Rocía el pollo y las papas con aceite de oliva.',
        'Sazona con sal, pimienta y hierbas aromáticas al gusto.',
        'Si deseas, puedes agregar rodajas de limón sobre el pollo para darle sabor.',
        'Hornea durante aproximadamente 1 hora o hasta que el pollo esté bien cocido y las papas estén doradas.',
        'Retira del horno y deja reposar antes de servir.',
        'Disfruta de un delicioso pollo al horno con papas.',
      ],
    },
    {
      id:2,
      nombre: 'Ensalada de quinoa',
      ingredientes: [
        '1 taza de quinoa',
        '2 tazas de agua',
        '1 pepino',
        '1 pimiento rojo',
        '1 tomate',
        '1 cebolla morada',
        'Jugo de limón',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
        'Perejil fresco picado (opcional)',
      ],
      pasos: [
        'Enjuaga la quinoa bajo agua fría para eliminar el sabor amargo.',
        'En una olla, combina la quinoa y el agua. Lleva a ebullición, luego reduce el fuego y cocina a fuego lento durante 15-20 minutos o hasta que la quinoa esté tierna y haya absorbido el agua.',
        'Retira la quinoa del fuego y déjala reposar durante 5 minutos.',
        'Mientras tanto, corta el pepino, el pimiento rojo, el tomate y la cebolla en trozos pequeños.',
        'En un tazón grande, mezcla la quinoa cocida con las verduras cortadas.',
        'Aliña la ensalada con jugo de limón, aceite de oliva, sal y pimienta al gusto. Mezcla bien.',
        'Espolvorea perejil fresco picado sobre la ensalada si lo deseas.',
        'Refrigera la ensalada de quinoa durante al menos 1 hora antes de servirla.',
        'Disfruta de una refrescante ensalada de quinoa.',
      ],
    },
    {
      id:3,
      nombre: 'Sopa de verduras',
      ingredientes: [
        '2 zanahorias',
        '2 papas',
        '1 cebolla',
        '2 dientes de ajo',
        '1 calabacín',
        '1 tomate',
        '100g de judías verdes',
        '1 litro de caldo de verduras',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
        'Hierbas aromáticas (opcional)',
      ],
      pasos: [
        'Lava y corta las verduras en trozos pequeños.',
        'En una olla grande, calienta un poco de aceite de oliva y sofríe la cebolla y el ajo picados hasta que estén dorados.',
        'Agrega las zanahorias, las papas, el calabacín, el tomate y las judías verdes a la olla. Cocina por unos minutos.',
        'Vierte el caldo de verduras en la olla y sazona con sal, pimienta y hierbas aromáticas al gusto.',
        'Lleva la sopa a ebullición, luego reduce el fuego y cocina a fuego lento durante aproximadamente 20-25 minutos o hasta que las verduras estén tiernas.',
        'Retira la sopa del fuego y deja que se enfríe un poco.',
        'Utiliza una batidora de mano o una licuadora para triturar la sopa hasta obtener una consistencia suave.',
        'Vuelve a calentar la sopa si es necesario antes de servir.',
        'Sirve la sopa de verduras caliente y disfruta.',
      ],
    },
    {
      id:4,
      nombre: 'Pizza casera',
      ingredientes: [
        'Masa para pizza',
        'Salsa de tomate',
        'Queso mozzarella',
        'Jamón',
        'Champiñones',
        'Pimiento verde',
        'Cebolla',
        'Aceitunas negras',
        'Orégano',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
      ],
      pasos: [
        'Precalienta el horno a la temperatura indicada en la masa para pizza.',
        'Extiende la masa para pizza en una bandeja para horno previamente engrasada o cubierta con papel de hornear.',
        'Unta la salsa de tomate sobre la masa de pizza de manera uniforme.',
        'Cubre la salsa con queso mozzarella rallado.',
        'Añade los ingredientes adicionales como jamón, champiñones, pimiento verde, cebolla y aceitunas negras al gusto.',
        'Espolvorea orégano, sal y pimienta al gusto sobre la pizza.',
        'Rocía un poco deaceite de oliva sobre la pizza para darle brillo y sabor adicional.',
        'Hornea la pizza según las instrucciones de la masa hasta que esté dorada y el queso esté derretido.',
        'Retira la pizza del horno y déjala enfriar un poco antes de cortarla y servirla.',
        'Disfruta de una deliciosa pizza casera hecha a tu gusto.',
      ],
    },
    {
      id:5,
      nombre: 'Arroz con pollo',
      ingredientes: [
        '2 tazas de arroz',
        '4 muslos de pollo',
        '1 cebolla',
        '2 dientes de ajo',
        '1 pimiento rojo',
        '1 zanahoria',
        '100g de guisantes',
        'Aceite de oliva',
        'Caldo de pollo',
        'Azafrán (opcional)',
        'Sal y pimienta al gusto',
      ],
      pasos: [
        'En una olla grande, calienta un poco de aceite de oliva y dorar los muslos de pollo hasta que estén bien cocidos. Retíralos de la olla y reserva.',
        'En la misma olla, sofríe la cebolla picada, el ajo picado y el pimiento rojo picado hasta que estén dorados.',
        'Agrega la zanahoria rallada y los guisantes a la olla y cocina por unos minutos.',
        'Añade el arroz y revuelve bien para que se mezcle con las verduras.',
        'Vuelve a colocar los muslos de pollo en la olla y vierte suficiente caldo de pollo para cubrir el arroz y el pollo.',
        'Sazona con sal, pimienta y azafrán al gusto.',
        'Cocina a fuego lento durante aproximadamente 15-20 minutos o hasta que el arroz esté tierno y haya absorbido el líquido.',
        'Retira la olla del fuego y deja reposar durante unos minutos antes de servir.',
        'Sirve el arroz con pollo caliente y disfruta de esta clásica receta.',
      ],
    },
    {
      id:6,
      nombre: 'Galletas de avena y pasas',
      ingredientes: [
        '1 taza de avena',
        '1 taza de harina',
        '1/2 taza de azúcar',
        '1/2 taza de mantequilla',
        '1 huevo',
        '1 cucharadita de esencia de vainilla',
        '1/2 cucharadita de bicarbonato de sodio',
        '1/2 taza de pasas',
        '1 pizca de sal',
      ],
      pasos: [
        'Precalienta el horno a 180°C (350°F).',
        'En un tazón, mezcla la mantequilla y el azúcar hasta obtener una textura suave y cremosa.',
        'Añade el huevo y la esencia de vainilla al tazón y mezcla bien.',
        'En otro tazón, combina la harina, la avena, el bicarbonato de sodio y la sal.',
        'Agrega la mezcla de harina al tazón de mantequilla y azúcar, y mezcla hasta obtener una masa homogénea.',
        'Incorpora las pasas a la masa y mezcla nuevamente.',
        'Forma pequeñas bolitas con la masa y colócalas en una bandeja para hornear previamente engrasada o cubierta con papel de hornear.',
        'Aplasta ligeramente cada bolita con un tenedor.',
        'Hornea durante aproximadamente 10-12 minutos o hasta que las galletas estén doradas en los bordes.',
        'Retira las galletas del horno y déjalas enfriar en la bandeja antes de transferirlas a una rejilla de enfriamiento.',
        'Disfruta de unas deliciosas galletas de avena y pasas.',
      ],
    },
    {
      id:7,
      nombre: 'Lasaña de carne',
      ingredientes: [
        '300g de carne molida',
        '1 cebolla',
        '2 dientes de ajo',
        '1 zanahoria',
        '1 lata de tomate triturado',
        '1 cucharada de pasta de tomate',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
        'Orégano',
        'Queso parmesano rallado',
        'Placas de lasaña',
        'Bechamel (salsa blanca)',
      ],
      pasos: [
        'En una sartén grande, calienta un poco de aceite de oliva y sofríe la cebolla y el ajo picados hasta que estén dorados.',
        'Agrega la carne molida a la sartén y cocínala hasta que esté bien dorada y cocida.',
        'Añade la zanahoria rallada, el tomate triturado y la pasta de tomate a la sartén. Mezcla bien y deja cocinar a fuego lento durante unos minutos.',
        'Sazona la salsa con sal, pimienta y orégano al gusto.',
        'Precalienta el horno a 180°C (350°F).',
        'En una bandeja para horno, coloca una capa de placas de lasaña.',
        'Añade una capa de salsa de carne sobre las placas de lasaña.',
        'Repite el proceso de capas alternando entre las placas de lasaña y la salsa de carne hasta que se agoten los ingredientes.',
        'Termina con una capa de placas de lasaña y cúbrelo todo con la salsa bechamel.',
        'Espolvorea queso parmesano rallado sobre la salsa bechamel.',
        'Hornea durante aproximadamente 30-35 minutos o hasta que la lasaña esté burbujeante y dorada en la superficie.',
        'Retira la lasaña del horno y déjala reposar durante unos minutos antes de servir.',
        'Disfruta de una deliciosa lasaña de carne casera.',
      ],
    },
    {
      id:8,
      nombre: 'Sopa de lentejas',
      ingredientes: [
        '1 taza de lentejas',
        '1 cebolla',
        '2 dientes de ajo',
        '1 zanahoria',
        '1 pimiento rojo',
        '1 tomate',
        '2 hojas de laurel',
        'Aceite de oliva',
        'Sal y pimienta al gusto',
        'Caldo de verduras',
        'Vinagre de vino tinto (opcional)',
      ],
      pasos: [
        'Enjuaga las lentejas bajo agua fría y déjalas escurrir.',
        'En una olla grande, calienta un poco de aceite de oliva y sofríe la cebolla picada y el ajo picado hasta que estén dorados.',
        'Agrega la zanahoria, el pimiento rojo y el tomate picados a la olla. Cocina por unos minutos.',
        'Añade las lentejas a la olla junto con las hojas de laurel.',
        'Vierte suficiente caldo de verduras en la olla para cubrir las lentejas.',
        'Sazona con sal y pimienta al gusto.',
        'Lleva la sopa a ebullición, luego reduce el fuego y cocina a fuego lento durante aproximadamente 30-40 minutos o hasta que las lentejas estén tiernas.',
        'Retira las hojas de laurel de la olla antes de servir.',
        'Si lo deseas, puedes agregar un chorrito de vinagre de vino tinto justo antes de servir para realzar el sabor.',
        'Sirve la sopa de lentejas caliente y disfruta.',
      ],
    },
    {
      id:9,
      nombre: 'Tarta de manzana',
      ingredientes: [
        'Masa quebrada',
        '4 manzanas',
        '1/2 taza de azúcar',
        '2 cucharadas de harina',
        '1 cucharadita de canela',
        'Jugo de medio limón',
        'Mantequilla',
        'Azúcar glas (opcional)',
      ],
      pasos: [
        'Precalienta el horno a 180°C (350°F).',
        'Extiende la masa quebrada en un molde para tarta previamente engrasado.',
        'Pela y corta las manzanas en rodajas finas.',
        'En un tazón, mezcla el azúcar, la harina y la canela.',
        'Agrega las rodajas de manzana al tazón y rocíalas con el jugo de limón. Mezcla bien para que las manzanas se cubran con la mezcla de azúcar y especias.',
        'Coloca las rodajas de manzana sobre la masa quebrada en el molde, asegurándote de que estén distribuidas de manera uniforme.',
        'Corta pequeños trozos de mantequilla y colócalos sobre las manzanas.',
        'Dobla los bordes de la masa hacia adentro para formar un borde alrededor de la tarta.',
        'Hornea durante aproximadamente 40-45 minutos o hasta que la masa esté dorada y las manzanas estén tiernas.',
        'Retira la tarta del horno y déjala enfriar antes de espolvorear azúcar glas por encima, si lo deseas.',
        'Disfruta de una deliciosa tarta de manzana casera.',
      ],
    },
    {
      id:10,
      nombre: 'Pasta Alfredo',
      ingredientes: [
        '250g de pasta (espagueti, fetuccini, etc.)',
        '200ml de crema para batir',
        '100g de queso parmesano rallado',
        '2 dientes de ajo',
        '2 cucharadas de mantequilla',
        'Sal y pimienta al gusto',
        'Perejil fresco picado (opcional)',
      ],
      pasos: [
        'Cocina la pasta en agua con sal según las instrucciones del paquete hasta que esté al dente. Luego, escúrrela y reserva.',
        'En una sartén grande, derrite la mantequilla a fuego medio.',
        'Agrega los dientes de ajo picados a la sartén y cocina hasta que estén dorados y fragantes.',
        'Vierte la crema para batir en la sartén y lleva a ebullición. Reduce el fuego y cocina a fuego lento durante unos minutos.',
        'Añade el queso parmesano rallado a la salsa y mezcla hasta que se derrita y se combine bien.',
        'Sazona la salsa con sal y pimienta al gusto.',
        'Agrega la pasta cocida a la sartén y mezcla para que se cubra con la salsa.',
        'Cocina por unos minutos más hasta que la pasta esté caliente y bien impregnada de la salsa.',
        'Espolvorea perejil fresco picado sobre la pasta antes de servir, si lo deseas.',
        'Sirve la pasta Alfredo caliente y disfruta de esta deliciosa receta.',
      ],
    },
    {
      id:11,
      nombre: 'Salmón a la parrilla',
      ingredientes: [
        '2 filetes de salmón',
        'Jugo de medio limón',
        '2 cucharadas de aceite de oliva',
        'Sal y pimienta al gusto',
        'Especias (opcional, como eneldo, pimentón, ajo en polvo)',
      ],
      pasos: [
        'Precalienta la parrilla a fuego medio-alto.',
        'En un tazón pequeño, mezcla el jugo de limón, el aceite de oliva, la sal, la pimienta y las especias si las estás utilizando.',
        'Cepilla los filetes de salmón con la mezcla de marinada por ambos lados.',
        'Coloca los filetes de salmón en la parrilla caliente, con el lado de la piel hacia abajo.',
        'Cocina durante aproximadamente 4-5 minutos por cada lado, o hasta que el salmón esté cocido pero aún jugoso en el centro.',
        'Retira los filetes de salmón de la parrilla y deja que descansen durante unos minutos antes de servir.',
        'Sirve el salmón a la parrilla con una guarnición de tu elección, como arroz, ensalada o verduras al vapor.',
        'Disfruta de un delicioso salmón a la parrilla lleno de sabor.',
      ],
    },
    {
      id:12,
      nombre: 'Tacos de carne asada',
      ingredientes: [
        '500g de carne de res (bistec, falda, etc.)',
        'Jugo de 2 limones',
        '2 dientes de ajo',
        '1 cebolla',
        '1 pimiento verde',
        '1 manojo de cilantro',
        'Tortillas de maíz',
        'Aceite vegetal',
        'Sal y pimienta al gusto',
        'Salsa picante (opcional)',
      ],
      pasos: [
        'En un tazón, mezcla el jugo de limón, los dientes de ajo picados, sal y pimienta.',
        'Añade la carne de res al tazón y marina durante al menos 1 hora en el refrigerador.',
        'En una sartén grande, calienta un poco de aceite vegetal a fuego medio-alto.',
        'Agrega la cebolla y el pimiento verde cortados en juliana a la sartén y cocina hasta que estén dorados y tiernos.',
        'Retira la cebolla y el pimiento de la sartén y reserva.',
        'En la misma sartén, cocina la carne de res marinada hasta que esté dorada por todos lados y cocida según tu preferencia.',
        'Retira la carne de la sartén y déjala reposar durante unos minutos antes de cortarla en tiras delgadas.',
        'Calienta las tortillas de maíz en la sartén o en el microondas hasta que estén calientes y flexibles.',
        'Rellena cada tortilla con tiras de carne de res, cebolla, pimiento y cilantro fresco.',
        'Si lo deseas, agrega salsa picante u otros condimentos a tus tacos.',
        'Sirve los tacos de carne asada calientes y disfruta de esta deliciosa comida.',
      ],
    },
    {
      id:13,
      nombre: 'Pan casero',
      ingredientes: [
        '500g de harina',
        '10g de levadura fresca (o 5g de levadura seca)',
        '300ml de agua tibia',
        '1 cucharadita de sal',
        '1 cucharadita de azúcar',
        'Aceite de oliva',
      ],
      pasos: [
        'En un tazón pequeño, disuelve la levadura y el azúcar en agua tibia. Deja reposar durante 5-10 minutos hasta que la mezcla se vuelva espumosa.',
        'En un tazón grande, mezcla la harina y la sal.',
        'Agrega la mezcla de levadura al tazón de harina y mezcla hasta que se forme una masa.',
        'Amasa la masa sobre una superficie enharinada durante unos 5-10 minutos hasta que esté suave y elástica.',
        'Forma una bola con la masa y colócala en un tazón ligeramente engrasado con aceite de oliva. Cubre el tazón con un paño húmedo y deja que la masa repose en un lugar cálido durante aproximadamente 1 hora o hasta que duplique su tamaño.',
        'Precalienta el horno a 220°C (425°F).',
        'Coloca la masa en una bandeja para hornear previamente engrasada o cubierta con papel de hornear.',
        'Hornea durante aproximadamente 20-25 minutos o hasta que el pan esté dorado en la superficie y suene hueco al golpearlo en la parte inferior.',
        'Retira el pan del horno y déjalo enfriar en una rejilla antes de cortarlo y servirlo.',
        'Disfruta de un delicioso pan casero recién horneado.',
      ],
    },
  ];
  
  console.log(recetasCocina);